name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get install -y build-essential

    - name: Build with Makefile
      run: make

    - name: Run test
      run: make test
